day10 : src/main.cpp src/Factory.cpp src/Reciever/Bot.cpp src/Instruction/GiveInstruction.cpp
	g++ -o day10 src/main.cpp src/Factory.cpp src/Reciever/Bot.cpp src/Instruction/GiveInstruction.cpp -std=c++11

clean :
	rm day10
